### ISSUE TITLE
stylelint

### ISSUE THREAD

**Issue by arlgnv** [AndreiReznikov/metalamp-layout#11]
Отсутствует линтер стилей. Для учебного проекта думаю будет достаточно установить оф. конфиг от stylelint'а.
*На боевых проектах всегда используются линтеры стилей. Причин этому опять же таки много) Как один из аргументов - хорошо, когда код во всех файлах выглядит одинаковым: в процессе работы на проекте ты привыкаешь к "духу"(стилю) кода и тебе легче ориентироваться в проекте.*

**Comment by arlgnv** [comment]
Зачем это?
![image](https://github.com/AndreiReznikov/metalamp-layout/assets/46949445/cc4f6647-225a-49c5-aeeb-aa606dddf094)

**Comment by AndreiReznikov** [comment]
Игнорирование файлов добавил из-за того, что линтер ругался на специфические классы библиотеки air-datepicker и на БЭМ модификаторы/элементы компонента button (в стандартном конфиге, видимо, эти случаи не учтены). Думаю, что это плохая практика, т.к. можно пропустить нарушение правил, которые нарушать нельзя. Игнорирование файлов убрал, добавил проверку классов регулярными выражениями.
